name: Update Calendar

on:
  schedule:
    - cron: '0 * * * *'  # This runs the job every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          ICAL_URL: ${{ secrets.ICAL_URL }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          echo "${{ secrets.CREDENTIALS_JSON }}" > credentials.json
          python update_calendar.py

